const generateTemplateBody = ({
  icon,
  appleLogo,
  hero,
  strip,
  logo,
  name,
  organizationName,
  description,
  website,
  phone,
  vip,
  location,
  lockScreenMessage,
}) => {
  return {
    name,
    protocol: "SINGLE_USE_COUPON",
    revision: 1,
    defaultLanguage: "EN",
    organizationName,
    localizedOrganizationName: null,
    description,
    localizedDescription: null,
    data: {
      dataFields: [
        {
          uniqueName: "singleUseCoupons.couponOffer.offerShortTitle",
          templateId: "",
          fieldType: "PROTOCOL_FIELDS",
          isRequired: false,
          label: "",
          localizedLabel: null,
          dataType: "TEXT",
          defaultValue: "",
          localizedDefaultValue: null,
          validation: "",
          userCanSetValue: false,
          currencyCode: "",
          appleWalletFieldRenderOptions: {
            textAlignment: "LEFT",
            positionSettings: {
              section: "PRIMARY_FIELDS",
              priority: 0,
            },
            changeMessage: "",
            localizedChangeMessage: null,
            dateStyle: "DATE_TIME_STYLE_DO_NOT_USE",
            timeStyle: "DATE_TIME_STYLE_DO_NOT_USE",
            numberStyle: "NUMBER_STYLE_DO_NOT_USE",
            suppressLinkDetection: [],
            ignoreTimezone: false,
            isRelativeDate: false,
          },
          dataCollectionFieldRenderOptions: {
            helpText: "",
            localizedHelpText: null,
            displayOrder: 0,
            placeholder: "",
            selectOptions: [],
            localizedPlaceholder: null,
            autocomplete: false,
            addressRenderOptions: null,
            localizedYearPlaceholder: "",
            localizedMonthPlaceholder: "",
            localizedDayPlaceholder: "",
          },
          usage: ["USAGE_APPLE_WALLET", "USAGE_GOOGLE_PAY"],
          googlePayFieldRenderOptions: {
            googlePayPosition: "GOOGLE_PAY_OFFER_SHORT_TITLE",
            textModulePriority: 0,
          },
          defaultTelCountryCode: "",
        },

        {
          uniqueName: "universal.expiryDate",
          templateId: "",
          fieldType: "UNIVERSAL_FIELDS",
          isRequired: false,
          label: "Expires",
          localizedLabel: null,
          dataType: "DATE_YYYYMMDD",
          defaultValue: "${universal.expiryDate}",
          localizedDefaultValue: null,
          validation: "",
          userCanSetValue: false,
          currencyCode: "",
          appleWalletFieldRenderOptions: {
            textAlignment: "LEFT",
            positionSettings: {
              section: "SECONDARY_FIELDS",
              priority: 0,
            },
            changeMessage: "",
            localizedChangeMessage: null,
            dateStyle: "DATE_TIME_STYLE_SHORT",
            timeStyle: "DATE_TIME_STYLE_DO_NOT_USE",
            numberStyle: "NUMBER_STYLE_DO_NOT_USE",
            suppressLinkDetection: [],
            ignoreTimezone: false,
            isRelativeDate: false,
          },
          dataCollectionFieldRenderOptions: {
            helpText: "",
            localizedHelpText: null,
            displayOrder: 0,
            placeholder: "",
            selectOptions: [],
            localizedPlaceholder: null,
            autocomplete: false,
            addressRenderOptions: null,
            localizedYearPlaceholder: "",
            localizedMonthPlaceholder: "",
            localizedDayPlaceholder: "",
          },
          usage: ["USAGE_APPLE_WALLET", "USAGE_GOOGLE_PAY"],
          googlePayFieldRenderOptions: {
            googlePayPosition: "GOOGLE_PAY_TEXT_MODULE",
            textModulePriority: 0,
          },
          defaultTelCountryCode: "",
        },

        {
          uniqueName: "singleUseCoupons.couponOffer.offerTitle",
          templateId: "",
          fieldType: "PROTOCOL_FIELDS",
          isRequired: false,
          label: "",
          localizedLabel: null,
          dataType: "TEXT",
          defaultValue: "",
          localizedDefaultValue: null,
          validation: "",
          userCanSetValue: false,
          currencyCode: "",
          appleWalletFieldRenderOptions: {
            textAlignment: "RIGHT",
            positionSettings: {
              section: "SECONDARY_FIELDS",
              priority: 2,
            },
            changeMessage: "",
            localizedChangeMessage: null,
            dateStyle: "DATE_TIME_STYLE_DO_NOT_USE",
            timeStyle: "DATE_TIME_STYLE_DO_NOT_USE",
            numberStyle: "NUMBER_STYLE_DO_NOT_USE",
            suppressLinkDetection: [],
            ignoreTimezone: false,
            isRelativeDate: false,
          },
          dataCollectionFieldRenderOptions: {
            helpText: "",
            localizedHelpText: null,
            displayOrder: 0,
            placeholder: "",
            selectOptions: [],
            localizedPlaceholder: null,
            autocomplete: false,
            addressRenderOptions: null,
            localizedYearPlaceholder: "",
            localizedMonthPlaceholder: "",
            localizedDayPlaceholder: "",
          },
          usage: ["USAGE_APPLE_WALLET", "USAGE_GOOGLE_PAY"],
          googlePayFieldRenderOptions: {
            googlePayPosition: "GOOGLE_PAY_OFFER_TITLE",
            textModulePriority: 2,
          },
          defaultTelCountryCode: "",
        },

        {
          uniqueName: "singleUseCoupons.couponOffer.offerDetails",
          templateId: "",
          fieldType: "PROTOCOL_FIELDS",
          isRequired: false,
          label: "TERM and conditions",
          localizedLabel: null,
          dataType: "TEXT_LONG",
          defaultValue: "",
          localizedDefaultValue: null,
          validation: "",
          userCanSetValue: false,
          currencyCode: "",
          appleWalletFieldRenderOptions: {
            textAlignment: "LEFT",
            positionSettings: {
              section: "BACK_FIELDS",
              priority: 0,
            },
            changeMessage: "",
            localizedChangeMessage: null,
            dateStyle: "DATE_TIME_STYLE_DO_NOT_USE",
            timeStyle: "DATE_TIME_STYLE_DO_NOT_USE",
            numberStyle: "NUMBER_STYLE_DO_NOT_USE",
            suppressLinkDetection: [],
            ignoreTimezone: false,
            isRelativeDate: false,
          },
          dataCollectionFieldRenderOptions: {
            helpText: "",
            localizedHelpText: null,
            displayOrder: 0,
            placeholder: "",
            selectOptions: [],
            localizedPlaceholder: null,
            autocomplete: false,
            addressRenderOptions: null,
            localizedYearPlaceholder: "",
            localizedMonthPlaceholder: "",
            localizedDayPlaceholder: "",
          },
          usage: ["USAGE_APPLE_WALLET", "USAGE_GOOGLE_PAY"],
          googlePayFieldRenderOptions: {
            googlePayPosition: "GOOGLE_PAY_OFFER_DETAILS",
            textModulePriority: 0,
          },
          defaultTelCountryCode: "",
        },

        {
          uniqueName: "custom.website",
          templateId: "",
          fieldType: "CUSTOM_FIELDS",
          isRequired: false,
          label: "Website",
          localizedLabel: null,
          dataType: "TEXT_LONG",
          defaultValue: website,
          localizedDefaultValue: null,
          validation: "",
          userCanSetValue: true,
          currencyCode: "",
          appleWalletFieldRenderOptions: {
            textAlignment: "CENTER",
            positionSettings: {
              section: "BACK_FIELDS",
              priority: 1,
            },
            changeMessage: "",
            localizedChangeMessage: null,
            dateStyle: "DATE_TIME_STYLE_DO_NOT_USE",
            timeStyle: "DATE_TIME_STYLE_DO_NOT_USE",
            numberStyle: "NUMBER_STYLE_DO_NOT_USE",
            suppressLinkDetection: ["LINK_DETECTOR_URL"],
            ignoreTimezone: false,
            isRelativeDate: false,
          },
          dataCollectionFieldRenderOptions: {
            helpText: "",
            localizedHelpText: null,
            displayOrder: 0,
            placeholder: "",
            selectOptions: [],
            localizedPlaceholder: null,
            autocomplete: false,
            addressRenderOptions: null,
            localizedYearPlaceholder: "",
            localizedMonthPlaceholder: "",
            localizedDayPlaceholder: "",
          },
          usage: ["USAGE_APPLE_WALLET", "USAGE_GOOGLE_PAY"],
          googlePayFieldRenderOptions: {
            googlePayPosition: "GOOGLE_PAY_TEXT_MODULE",
            textModulePriority: 3,
          },
          defaultTelCountryCode: "",
        },

        {
          uniqueName: "custom.phone",
          templateId: "",
          fieldType: "CUSTOM_FIELDS",
          isRequired: false,
          label: "Service Department Phone #",
          localizedLabel: null,
          dataType: "TEXT_LONG",
          defaultValue: phone,
          localizedDefaultValue: null,
          validation: "",
          userCanSetValue: true,
          currencyCode: "",
          appleWalletFieldRenderOptions: {
            textAlignment: "CENTER",
            positionSettings: {
              section: "BACK_FIELDS",
              priority: 2,
            },
            changeMessage: "",
            localizedChangeMessage: null,
            dateStyle: "DATE_TIME_STYLE_DO_NOT_USE",
            timeStyle: "DATE_TIME_STYLE_DO_NOT_USE",
            numberStyle: "NUMBER_STYLE_DO_NOT_USE",
            suppressLinkDetection: ["LINK_DETECTOR_PHONE"],
            ignoreTimezone: false,
            isRelativeDate: false,
          },
          dataCollectionFieldRenderOptions: {
            helpText: "",
            localizedHelpText: null,
            displayOrder: 0,
            placeholder: "",
            selectOptions: [],
            localizedPlaceholder: null,
            autocomplete: false,
            addressRenderOptions: null,
            localizedYearPlaceholder: "",
            localizedMonthPlaceholder: "",
            localizedDayPlaceholder: "",
          },
          usage: ["USAGE_APPLE_WALLET", "USAGE_GOOGLE_PAY"],
          googlePayFieldRenderOptions: {
            googlePayPosition: "GOOGLE_PAY_TEXT_MODULE",
            textModulePriority: 2,
          },
          defaultTelCountryCode: "",
        },

        {
          uniqueName: "custom.vip",
          templateId: "",
          fieldType: "CUSTOM_FIELDS",
          isRequired: false,
          label: "VIP OFFER",
          localizedLabel: null,
          dataType: "TEXT_LONG",
          defaultValue: vip,
          localizedDefaultValue: null,
          validation: "",
          userCanSetValue: true,
          currencyCode: "",
          appleWalletFieldRenderOptions: {
            textAlignment: "RIGHT",
            positionSettings: {
              section: "BACK_FIELDS",
              priority: 3,
            },
            changeMessage: "",
            localizedChangeMessage: null,
            dateStyle: "DATE_TIME_STYLE_DO_NOT_USE",
            timeStyle: "DATE_TIME_STYLE_DO_NOT_USE",
            numberStyle: "NUMBER_STYLE_DO_NOT_USE",
            suppressLinkDetection: [],
            ignoreTimezone: false,
            isRelativeDate: false,
          },
          dataCollectionFieldRenderOptions: {
            helpText: "",
            localizedHelpText: null,
            displayOrder: 0,
            placeholder: "",
            selectOptions: [],
            localizedPlaceholder: null,
            autocomplete: false,
            addressRenderOptions: null,
            localizedYearPlaceholder: "",
            localizedMonthPlaceholder: "",
            localizedDayPlaceholder: "",
          },
          usage: ["USAGE_APPLE_WALLET", "USAGE_GOOGLE_PAY"],
          googlePayFieldRenderOptions: {
            googlePayPosition: "GOOGLE_PAY_TEXT_MODULE",
            textModulePriority: 1,
          },
          defaultTelCountryCode: "",
        },
      ],
      dataCollectionPageSettings: {
        title: "Provide coupon details below",
        localizedTitle: null,
        description: "",
        localizedDescription: null,
        submitButtonText: "Create Coupon",
        localizedSubmitButtonText: null,
        loadingText: "Hang on",
        localizedLoadingText: null,
        thankYouText: "Thank you, we will redirect you to your pass.",
        localizedThankYouText: null,
        pageBackgroundColor: "",
        localizedPageBackgroundColor: null,
        trackingSettings: null,
        submitButtonTextColor: "",
        submitButtonBackgroundColor: "",
        footerText: "",
        localizedFooterText: null,
        cssOverrides: "",
        passwordSettings: null,
      },
    },
    imageIds: {
      icon: icon,
      logo: logo,
      appleLogo: appleLogo,
      hero: hero,
      eventStrip: "",
      strip: strip,
      thumbnail: "",
      background: "",
      footer: "",
      security: "",
      privilege: "",
      airlineAlliance: "",
      personalization: "",
      banner: "",
      message: "",
      profile: "",
      appImage: "",
      stampedImage: "",
      unstampedImage: "",
      stampImage: "",
    },
    colors: {
      backgroundColor: "#ffffff",
      labelColor: "#000000",
      textColor: "#000000",
      stripColor: "",
    },
    barcode: {
      payload: "${singleUseCoupons.coupon.sku}",
      format: "PDF417",
      altText: " ${singleUseCoupons.coupon.sku}",
      localizedAltText: null,
      messageEncoding: "utf8",
      suppressSecurity: false,
      rotatingBarcode: false,
      totpParameters: null,
    },
    nfcEnabled: {
      enabled: false,
      certificateId: "",
      payload: "",
    },
    sharing: {
      prohibitSharing: false,
      url: "",
      description: "",
      localizedDescription: null,
    },
    appleWalletSettings: {
      passType: "COUPON",
      userInfo: "",
      appLaunchUrl: "",
      associatedStoreIdentifiers: [],
      maxDistance: 0,
      appStoreCountries: [],
      transitType: "TRANSIT_TYPE_DO_NOT_USE",
      groupingIdentifier: "",
      personalizationDetails: null,
      appStoreIdentifiers: [],
    },
    googlePaySettings: {
      passType: "OFFER",
      androidApp: null,
      iosApp: null,
      webApp: null,
      classTemplateInfo:
        '{"detailsTemplateOverride":{"detailsItemInfos":[]},"cardTemplateOverride":{"cardRowTemplateInfos":[]}}',
      backgroundColor: "",
      languageOverrides: [],
    },
    locations: [
      {
        lat: location.lat,
        lon: location.lng,
        lockScreenMessage,
      },
    ],
    beacons: [],
    timezone: "Asia/Karachi",
    expirySettings: {
      expiryType: "EXPIRE_NONE",
    },
    landingPageSettings: {
      landingLocalizationOverride: [],
      preferThirdPartyAndroidWallet: "OFF",
      preferredAndroidWallet: "ANDROID_WALLET_WALLETPASSES",
      localizedTextOverrides: {},
      Name: name,
      protocol: "SINGLE_USE_COUPON",
      revision: 1,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  };
};

module.exports = generateTemplateBody;
